lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
<<<<<<< Updated upstream

theme: jekyll-theme-cayman
=======
regeneration: -w
>>>>>>> Stashed changes
